---
title: Third Person Project
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
logo_image: "/uploads/ThirdPersonProjectLogo.png"
