---
title: Third Person Project
timezone: America/New_York
collections:
  finding:
    title: Findings
    output: true
    permalink: findings
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
  sass_dir: _sass
logo_image: "/uploads/ThirdPersonProjectLogo.png"
header_image: "/uploads/Wilmington%20NC%20-%20Bird_s%20Eye%20View%20c.%201900,%20New%20Hanover%20County%20LibraryJPG.jpg"
footer_content: Thanks for visiting! You can contact us at [email@address.com](mailto:email@address.com)
