---
title: Third Person Project
timezone: America/New_York
collections:
  archives:
    title: Archives
    output: true
    permalink: "/archives/:name/"
  findings:
    title: Findings
    output: true
    permalink: "/findings/:name/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:name/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    primary_image: ''
- scope:
    path: ''
    type: archives
  values:
    layout: item
    primary_image: ''
    file: ''
    transcript_text: ''
- scope:
    path: ''
    type: findings
  values:
    layout: item
    primary_image: ''
    author: ''
- scope:
    path: ''
    type: projects
  values:
    layout: item
sass:
  style: compressed
  sass_dir: _sass
logo_image: "/uploads/ThirdPersonProjectLogo.png"
primary_image: "/uploads/Wilmington%20NC%20-%20Bird_s%20Eye%20View%20c.%201900,%20New%20Hanover%20County%20LibraryJPG.jpg"
footer_content: Thanks for visiting! You can contact us at [email@address.com](mailto:email@address.com)
