---
title: Third Person Project
timezone: America/New_York
exclude:
- "server/"
collections:
  archives:
    title: Archives
    output: true
    permalink: "/archives/:name/"
  findings:
    title: Findings
    output: true
    permalink: "/findings/:name/"
  projects:
    title: Projects
    output: true
    permalink: "/projects/:name/"
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
  sass_dir: _sass
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'server']
