backend:
  name: github
  repo: minicreative/third-person-project
  branch: main
editor:
  preview: false
media_folder: "_uploads"
public_folder: "uploads"
collections:
  - name: "page"
    label: "Pages"
    label_singular: "Page"
    folder: "/"
    create: false
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "URL"
        name: "permalink"
        widget: "string"
      - label: "Collection"
        name: "collection"
        widget: "string"
        hint: "Collection to list on page (e.g. findings, archives). Leave blank if no list is needed"
      - label: "Content"
        name: "body"
        widget: "markdown"
        hint: "Displayed above list of items"
  - name: "findings"
    label: "Findings"
    label_singular: "Finding"
    folder: "_findings"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "item"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Published"
        name: "date"
        widget: "datetime"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "Primary Image"
        name: "primary_image"
        widget: "image"
        hint: "Image will be used as the cover photo for the page"
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "item"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Primary Image"
        name: "primary_image"
        widget: "image"
        hint: "Image will be used as the cover photo for the page"
      - label: "Content"
        name: "body"
        widget: "markdown"
      - label: "Press"
        label_singular: "Article"
        name: "press"
        widget: "list"
        summary: "{{fields.title}}"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Publication"
            name: "publication"
            widget: "string"
          - label: "Date"
            name: "date"
            widget: "datetime"
          - label: "URL"
            name: "url"
            widget: "string"
  - name: "archives"
    label: "Archived Items"
    label_singular: "Item"
    folder: "_archives"
    create: true
    slug: "{{slug}}"
    fields:
    - label: "Layout"
      name: "layout"
      widget: "hidden"
      default: "item"
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "PDF"
      name: "file"
      widget: "file"
    - label: "Published"
      name: "date"
      widget: "datetime"
      format: "MM/DD/YYYY"
    - label: "Primary Image"
      name: "primary_image"
      widget: "image"
      hint: "Image will be used as the cover photo for the page"
    - label: "Transcript"
      name: "body"
      widget: "markdown"
