backend:
  name: github
  repo: minicreative/third-person-project
  branch: main
  base_url: https://github-auth.tomasroy.com/
editor:
  preview: false
media_folder: "_uploads"
public_folder: "uploads"
collections:
  - name: "page"
    label: "Pages"
    create: false
    sortable_fields: ['title', 'order']
    files: 
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: permalink, widget: string}
          - {label: Order, name: order, widget: number}
          - label: "Header Background Slideshow"
            name: "primary_images"
            widget: "image"
            allow_multiple: true
          - label: "Header Text"
            name: "header_text"
            widget: "text"
          - label: "Featured Sections Header"
            name: "featured_sections_header"
            widget: "string"
          - label: "Featured Sections"
            name: "featured_sections"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Link, name: link, widget: string}
          - label: "About Header"
            name: "about_header"
            widget: string
          - label: "About Content"
            name: "about_content"
            widget: text
          - label: "About Link"
            name: "about_link"
            widget: "string"
          - label: "About Link URL"
            name: "about_link_url"
            widget: "string"
      - file: "projects.md"
        label: Projects
        name: projects
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: permalink, widget: string}
          - {label: Order, name: order, widget: number}
          - {label: Collection, name: collection, widget: string}
          - {label: Content, name: body, widget: markdown, hint: "Displayed above list of items"}
      - file: "archives.md"
        label: Archives
        name: archives
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: permalink, widget: string}
          - {label: Order, name: order, widget: number}
          - {label: Collection, name: collection, widget: string}
          - {label: Content, name: body, widget: markdown, hint: "Displayed above list of items"}
      - file: "findings.md"
        label: Findings
        name: findings
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: permalink, widget: string}
          - {label: Order, name: order, widget: number}
          - {label: Collection, name: collection, widget: string}
          - {label: Content, name: body, widget: markdown, hint: "Displayed above list of items"}
      - file: "about.md"
        label: About
        name: about
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: permalink, widget: string}
          - {label: Order, name: order, widget: number}
          - {label: Content, name: body, widget: markdown}
      - file: "get-involved.md"
        label: Get Involved
        name: get-involved
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: permalink, widget: string}
          - {label: Order, name: order, widget: number}
          - {label: Content, name: body, widget: markdown}
  - name: "findings"
    label: "Findings"
    label_singular: "Finding"
    folder: "_findings"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "item"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Published"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "Primary Image"
        name: "primary_image"
        widget: "image"
        hint: "Image will be used as the cover photo for the page"
      - label: "Content"
        name: "body"
        widget: "markdown"
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "item"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Primary Image"
        name: "primary_image"
        widget: "image"
        hint: "Image will be used as the cover photo for the page"
      - label: "Content"
        name: "body"
        widget: "markdown"
      - label: "Press"
        label_singular: "Article"
        name: "press"
        widget: "list"
        summary: "{{fields.title}}"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Publication"
            name: "publication"
            widget: "string"
          - label: "Date"
            name: "date"
            widget: "datetime"
          - label: "URL"
            name: "url"
            widget: "string"
  - name: "archives"
    label: "Archives"
    label_singular: "Archive Item"
    folder: "_archives"
    create: true
    slug: "{{slug}}"
    fields:
    - label: "Layout"
      name: "layout"
      widget: "hidden"
      default: "item"
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "PDF"
      name: "file"
      widget: "file"
    - label: "Published"
      name: "date"
      widget: "datetime"
      date_format: "YYYY-MM-DD"
    - label: "Primary Image"
      name: "primary_image"
      widget: "image"
      hint: "Image will be used as the cover photo for the page"
    - label: "Transcript"
      name: "body"
      widget: "markdown"
  - name: "config"
    label: "Site & Annotation App Settings"
    create: false
    files:
      - file: "_data/settings.yml"
        label: "Settings"
        name: "settings"
        fields:
          - label: "Logo"
            name: "logo_image"
            widget: image
          - label: "Default Header Image"
            name: "primary_image"
            widget: image
          - label: "Messages"
            name: "messages"
            widget: object
            fields:
              - label: "View transcript message"
                name: "view_transcript"
                widget: string
              - label: "View file message"
                name: "view_file"
                widget: string
              - label: "No transcript message"
                name: "no_transcript"
                widget: string
              - label: "No file message"
                name: "no_file"
                widget: string
          - label: "Footer Sections"
            name: "footer_sections"
            widget: "list"
            allow_add: false
            fields:
              - label: "CSS Class"
                name: "class"
                widget: "string"
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "HTML"
                name: "html"
                widget: "string"
      - file: "admin.md"
        label: "Annotations"
        name: "annotate"
        fields:
          - label: "Title"
            name: "title"
            widget: text
          - label: "Login Welcome Text"
            name: "login_welcome_text"
            widget: markdown
          - label: "Login Tab Text"
            name: "login_tab_text"
            widget: text
          - label: "Signup Tab Text"
            name: "signup_tab_text"
            widget: text
          - label: "Dashboard Welcome Text"
            name: "dashboard_welcome_text"
            widget: markdown
          - label: "Expired Text"
            name: "expired_text"
            widget: markdown
    
