name: Build & Publish Server

on:
  workflow_call:
    inputs:
      docker_name:
        description: The full name of your DockerHub repository, e.g. "my-docker-name/my-repo-name"
        required: true
        type: string
      kube_deployment:
        description: The name of your Kubernetes Deployment resource to update with your latest image tag
        required: true
        type: string
    secrets:
      docker_username:
        description: Your DockerHub username
        required: true
      docker_password:
        description: A Dockerhub Access Token with permissions to upload your container to Dockerhub
        required: true
      kube_config:
        description: A base64 encded string of your Kubernetes cluster's config file
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
    - name: Build and Push the Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ vars.docker_name }}:${{ github.sha }}, ${{ vars.docker_name }}:latest
  publish:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.kube_config }}
    - uses: actions/checkout@v3
    - name: Update Kubernetes deployment
      run: kubectl set image "deployment/${{ vars.kube_deployment }}" "main=${{ vars.docker_name }}:${{ github.sha }}"