name: Build & Publish
on:
  push:
    branches:
      - main
jobs:
  build-publish-jekyll:
    name: Build & Publish Jekyll
    uses: minicreative/build-publish-jekyll/.github/workflows/build-publish.yml@main
    with:
      docker_name: ${{ vars.website_docker_name }}
      kube_deployment: ${{ vars.website_kube_deployment }}
    secrets:
      docker_username: ${{ secrets.docker_username }}
      docker_password: ${{ secrets.docker_password }}
      kube_config: ${{ secrets.kube_config }}
  build-server:
    name: Build Server
    if: "contains(github.event.head_commit.message, '[server]')"
    uses: "./.github/workflows/build-publish-server.yml"
    with:
      docker_name: ${{ vars.server_docker_name }}
      kube_deployment: ${{ vars.server_kube_deployment }}
    secrets:
      docker_username: ${{ secrets.docker_username }}
      docker_password: ${{ secrets.docker_password }}
      kube_config: ${{ secrets.kube_config }}

